### PR TITLE
Skip orchestration if host is not of type Host::Managed

### LINKED ISSUE #59: Host discovery breaks due to missing host parameters
When [foreman_discovery](https://github.com/theforeman/foreman_discovery) is used, the discovery fails and shows an error on the host's console:
```
500: Discovery failed, code 422, reason: undefined method 'params' for #<Host::Discovered::0x00007facce1938e0> 
```
On the smartproxy:
```
2020-06-18T08:46:02 4d157ad9 [W] Discovery failed, code 422, reason: undefined method `params' for #<Host::Discovered:0x00007facce1938e0>
RuntimeError: Discovery failed, code 422, reason: undefined method `params' for #<Host::Discovered:0x00007facce1938e0>
/usr/share/gems/gems/smart_proxy_discovery-1.0.5/lib/smart_proxy_discovery/discovery_main.rb:18:in `create_discovered_host'
/usr/share/gems/gems/smart_proxy_discovery-1.0.5/lib/smart_proxy_discovery/discovery_api.rb:38:in `block in <class:InboundApi>'
[...]
```
We also see the matching error in Foreman itself:
```
NoMethodError: ********
  from active_model/attribute_methods.rb:430:in `method_missing'
  from audited/auditor.rb:99:in `method_missing'
  from foreman_git_templates/orchestration/tftp.rb:23:in `validate_tftp'
  from active_support/callbacks.rb:426:in `block in make_lambda'
[...]
```
The error is probably caused by this call for `params` on `Host::Discovered` which does not exist:
https://github.com/dm-drogeriemarkt/foreman_git_templates/blob/caa1cc6a3b46651fe88e9edeb3d93e527033a435/app/models/concerns/foreman_git_templates/orchestration/tftp.rb#L23

Adding a check solves the problem:
```ruby
def validate_tftp
    return super unless host.managed
    return super unless host.params['template_url']
    [...]
end
```

### PR DESCRIPTION
**Pull request by laugmanuel**
Closes #59

### CODE REVIEW

File: app/models/concerns/foreman_git_templates/orchestration/tftp.rb [hunk 1]
```diff
@@ -20,9 +20,9 @@ def generate_pxe_template(kind)
         private
 
         def validate_tftp
-          return super unless host.params['template_url']
           return unless tftp? || tftp6?
           return unless host.operatingsystem
+          return super unless host.params['template_url']
```
Comment (timogoebel) [inline app/models/concerns/foreman_git_templates/orchestration/tftp.rb:25]: I think we should make sure to have this as the first line in the method to make sure we don't introduce any regressions.
This concern is included into `Nic::Managed`. Can we add something like

```ruby
return super unless host.is_a?(Host::Managed)
```

Comment (laugmanuel) [reply app/models/concerns/foreman_git_templates/orchestration/tftp.rb]: I've changed it accordingly. Hopefully the complexity of the method does not reach it's limit ;)

File: app/models/concerns/foreman_git_templates/orchestration/tftp.rb [hunk 2]
```diff
@@ -29,6 +29,13 @@ def validate_tftp
 
           failure _('No %{kind} template was found for host %{host}. Repository url: %{url}') % { kind: pxe_kind, host: host.name, url: host.params['template_url'] }
         end
+
+        def host_supported?
```
Comment (timogoebel) [inline app/models/concerns/foreman_git_templates/orchestration/tftp.rb:33]: Nit: This is included into the Nic model, so this would read `nic.host_supported?` which isn't really descriptive.

```suggestion
        def feasible_for_git_template_rendering?
```

Comment (laugmanuel) [reply app/models/concerns/foreman_git_templates/orchestration/tftp.rb]: I've changed the name 👍

**Comment by timogoebel** [comment]
Thanks!
