### PR TITLE
Remove edit button for templates from git repository

### LINKED ISSUE #39: disable edit button for templates from git repository
On the host show page a `Templates` tab exists that shows all templates that are available for that host. Next to the host name, an edit button is displayed that does not work. We should disable or remove this button.

image

### PR DESCRIPTION
**Pull request by kamils-iRonin**
fixes #39 
image

### CODE REVIEW

File: app/helpers/foreman_git_templates/application_helper.rb [hunk 1]
```diff
@@ -0,0 +1,15 @@
+# frozen_string_literal: true
+
+module ForemanGitTemplates
+  module ApplicationHelper
+    def display_link_if_authorized(name, options = {}, html_options = {})
```
Comment (timogoebel) [inline app/helpers/foreman_git_templates/application_helper.rb]: Shouldn't this be a concern?

```ruby
module ForemanGitTemplates
  module ApplicationHelper
    include ActiveRecord::Concern

    module Overrides
      ...
    end

    included do
      preprend Overrides
    end
  end
end
```

**Comment by timogoebel** [comment]
Thanks, @kamils-iRonin.
